

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer";
import { SessionProvider } from "next-auth/react";
import type { ReactNode } from "react";


export const metadata: Metadata = {
  title: "Med.AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      
          <Navbar />
          <div className="container mx-auto px-[3vw] xl:px-[7vw]">
            <Toaster />
             
          {children}
       

            <Footer />
          </div>
        
      </body>
    </html>
  );
}
